---
title: "Course Resources"
subtitle: "GSD SES 5394"
output: 
  rmdformats::downcute
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This page includes resources for students to refer to as they work on course assignments.

# Skills overview pages

* [Assignment 2](https://gsd-ses-5394-s2022.github.io/Richmond/a2_skills.html){target="_blank"}
* [Assignment 4](https://gsd-ses-5394-s2022.github.io/Richmond/a4_skills.html){target="_blank"}
* [Assignment 5](https://gsd-ses-5394-s2022.github.io/Richmond/a5_skills.html){target="_blank"}
* [Assignment 6](https://gsd-ses-5394-s2022.github.io/Richmond/a6_skills.html){target="_blank"}
* [Assignment 7](https://gsd-ses-5394-s2022.github.io/Richmond/a7_skills.html){target="_blank"}
* [Assignment 8](https://gsd-ses-5394-s2022.github.io/Richmond/a8_skills.html){target="_blank"}
* [Assignment 9](https://gsd-ses-5394-s2022.github.io/Richmond/a9_skills.html){target="_blank"}

# Student work

I think it can be helpful to see what your classmates are producing. All GitHub repositories are public. Feel free to browse them for inspiration (and cite them if they're influencing your own choices).

## GitHub repositories

* [Austin](https://github.com/GSD-SES-5394-S2022/Austin){target="_blank"}
* [Buffalo](https://github.com/GSD-SES-5394-S2022/Buffalo){target="_blank"}
* [Denver](https://github.com/GSD-SES-5394-S2022/Denver){target="_blank"}
* [Salt Lake City](https://github.com/GSD-SES-5394-S2022/Salt-Lake){target="_blank"}
* [San Jose](https://github.com/GSD-SES-5394-S2022/San-Jose){target="_blank"}

## Report submissions

* [Austin](https://gsd-ses-5394-s2022.github.io/resources/student-reports/Austin.pdf){target="_blank"}
* Buffalo (coming soon)
* [Denver](https://gsd-ses-5394-s2022.github.io/resources/student-reports/Denver.pdf){target="_blank"}
* [Salt Lake City](https://gsd-ses-5394-s2022.github.io/resources/student-reports/Salt-Lake.pdf){target="_blank"}
* [San Jose](https://gsd-ses-5394-s2022.github.io/resources/student-reports/San-Jose.pdf){target="_blank"}

# Lecture notes

* [Lecture 1](https://gsd-ses-5394-s2022.github.io/resources/lecture-notes/Lecture1.pdf){target="_blank"}: Course introduction
* [Lecture 2](https://gsd-ses-5394-s2022.github.io/resources/lecture-notes/Lecture2.pdf){target="_blank"}: Envisioning the future: scenarios and alternatives
* [Lecture 3](https://gsd-ses-5394-s2022.github.io/resources/lecture-notes/Lecture3.pdf){target="_blank"}: Aggregation: defining traffic analysis zones
* Lecture 4: All models are wrong (slides are lost - ironically, I accidentally saved over them while preparing the slides on file management and version control)
* [Lecture 5](https://gsd-ses-5394-s2022.github.io/resources/lecture-notes/Lecture5.pdf){target="_blank"}: File management and version control
* Lecture 6: Open data, open source, open standards (no slides or notes)
* Lecture 7: GTFS and OpenStreetMap file formats (no slides or notes)
* [Lecture 8](https://gsd-ses-5394.github.io/accessibilty/){target="_blank"}: Accessibility concepts
* [Lecture 9](https://urban-stack.shinyapps.io/access-decay/){target="_blank"}: Accessibilty measurement
* Lecture 10: Predictors of vehicle access (no slides or notes)
* Lecture 11: Modeling vehicle access (no slides or notes)
* [Lecture 12](https://gsd-ses-5394-s2022.github.io/resources/lecture-notes/Lecture12.pdf){target="_blank"}: Trip generation concepts 
* [Lecture 13](https://gsd-ses-5394-s2022.github.io/resources/lecture-notes/Lecture13.pdf){target="_blank"}: Modeling trip generation based on household travel surveys
* Lecture 14: Mode choice concepts (no slides or notes)
* [Lecture 15](https://gsd-ses-5394-s2022.github.io/resources/lecture-notes/Lecture15.xlsx){target="_blank"}: Modeling trip distribution

# Potential final exam questions

* What are the four steps referenced in a traditional four-step travel demand model?
* What inputs are needed to generate a travel time skim?
* What inputs are needed to calculate accessibility?
* What is a traffic analysis zone?
* What are some problems with large traffic analysis zones?
* What are some problems with small traffic analysis zones?
* What is NCHRP 716?
* Who wrote the book Modelling Transport we've read from in this class?
* What is a logsum?
* What type of decay function is suited to a cumulative-opportunity-based accessibility measure?
* What type of decay function is suited to a gravity-based accessibility measure?
* What type of decay function is suited to a utility-based accessibility measure?
* Why would it be necessary to balance trip productions and attractions after estimating them?
* What is a typical approach to balancing trip productions and attractions?
* What is the difference (or relationship) between a trip and a tour?
* What is a trip origin?
* What is a trip destination?
* What is a trip production?
* What is a trip attraction?
* What does it mean for a trip to be "home-based"?
* What inputs are typically used to estimate a trip production model?
* What inputs are typically used to estimate a trip attraction model?
* What inputs do you need to estimate trip distribution using a gravity model?

